game:
  auto-start: true # For testing etc... do /forcestart
  spawn-points:
    -
  items-per-chest: 6

lobby:
  spawn:

border:
  enabled: true
  radius: 100
  death-match-radius: 50
  center:

data:
  map: "Default"